<?php
session_start();
if(isset($_SESSION['username'])){
  session_destroy();
  header('Location:http://localhost/fb/fblogin.html');
}
else{
  header('Location:http://localhost/fb/fblogin.html');
}